### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by davidgao** [BarclayII/AIMv6#1]
1. Drivers for same types of devices MUST have ISA-independent interfaces, so we need some headers for them.
2. We could possibly put interrupt controlling code in drivers directory.
3. usr looks like /usr, and may possibly be misleading. We can just use user to indicate user space code.

**Comment by BarclayII** [comment]
1. Sure, they could be put inside drivers/include I guess.
2. Interrupts are mainly an architecture or CPU specific issue, so it's better to put at least most of interrupt codes inside kern/arch/$ARCH, and headers inside kern/arch/$ARCH/include/asm.  Driver specific interrupts should be put inside drivers directory of course.
3. Renamed usr to user.
