### ISSUE TITLE
please move rtc driver into clock directory

### ISSUE THREAD

**Issue by davidgao** [BarclayII/AIMv6#9]
Title means almost everything,

I added a `sleep.h` to `include/`, they should be provided by some driver, but the signatures should be just the same.

**Comment by BarclayII** [comment]
Good point.

However I think `sleep()` functions should probably be renamed to `delay()` since `sleep()` is more-or-less a system call, and `delay()` hints for some kind of busy-wait which fits our requirements.

Date: Wed, 2 Sep 2015 09:42:51 -0700

**Comment by davidgao** [comment]
maybe `spin_sleep()` can indicate that better.

**Comment by BarclayII** [comment]
`spin_sleep`, `delay` and `busy_wait` are all good candidates, feel free to choose one or invent your own

发自 Windows 邮件

发件人: David Gao
发送时间: ‎2015‎年‎9‎月‎4‎日, ‎星期五 ‎18‎:‎52
收件人: BarclayII/AIMv6
抄送: Gan Quan

maybe spin_sleep() can indicate that better.

**Comment by davidgao** [comment]
it'll be `spin_sleep` then. ARM's other SDKs say `sleep` so choosing another name might be misleading.
